# Copyright 2025 The RLinf Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections.abc import Callable
from typing import Any

import torch


def compute_adjoint_states(
    f_beta_fn: Callable[[Any, torch.Tensor, torch.Tensor], torch.Tensor],
    obs: Any,
    xs: torch.Tensor,
    Q_grad_at_1: torch.Tensor,
    lambda_: float | torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Compute QAM lean adjoint states along a forward actor trajectory.

    The caller provides the forward trajectory ``xs`` generated by the current
    actor ``f_theta``. This helper only uses the frozen behavior velocity
    ``f_beta_fn`` to propagate the terminal critic gradient backward in time.
    It does not depend on workers, FSDP, or OpenPI-specific state.

    Following QAM Eq. (25), the VJP is taken through the complete behavior
    drift

    ``b_beta(x, t) = 2 * f_beta(obs, x, t) - x / t``,

    not through ``f_beta`` alone. The trajectory and returned adjoints are
    ordered by increasing flow time: ``xs[0]`` / ``adjs[0]`` correspond to
    ``t=0`` and ``xs[-1]`` / ``adjs[-1]`` correspond to ``t=1``. The reverse
    recursion only evaluates the drift at ``t > 0``.

    Args:
        f_beta_fn: Frozen behavior velocity function with signature
            ``(obs, x_t, timestep) -> velocity``. It may have frozen
            parameters, but must still build an autograd graph with respect to
            ``x_t`` so that VJP can be computed.
        obs: Observation payload passed through to ``f_beta_fn``.
        xs: Forward actor trajectory, shape ``[num_steps + 1, B, ...]``.
        Q_grad_at_1: Raw critic action gradient at ``xs[-1]``.
        lambda_: QAM temperature/regularization scale. The terminal adjoint is
            ``-Q_grad_at_1 / lambda_``.

    Returns:
        A pair ``(xs, adjs)`` with matching shape ``[num_steps + 1, B, ...]``.
    """
    if xs.ndim < 2:
        raise ValueError(f"xs must have shape [W+1, B, ...], got {tuple(xs.shape)}")
    if not xs.is_floating_point():
        raise TypeError(f"xs must be a floating point tensor, got {xs.dtype}")

    traj = xs.detach()
    num_steps = traj.shape[0] - 1
    if num_steps <= 0:
        raise ValueError(f"xs must contain at least two states, got {traj.shape[0]}")

    x1 = traj[-1]
    if x1.shape != Q_grad_at_1.shape:
        raise ValueError(
            "xs[-1] and Q_grad_at_1 must have the same shape, got "
            f"{tuple(x1.shape)} and {tuple(Q_grad_at_1.shape)}"
        )
    if not Q_grad_at_1.is_floating_point():
        raise TypeError(
            "Q_grad_at_1 must be a floating point tensor, "
            f"got {Q_grad_at_1.dtype}"
        )

    lambda_t = torch.as_tensor(lambda_, device=x1.device, dtype=x1.dtype)
    if bool(torch.any(lambda_t == 0).item()):
        raise ValueError("lambda_ must be non-zero")

    h = 1.0 / num_steps
    batch_size = x1.shape[0]

    def _time(value: float) -> torch.Tensor:
        return torch.full(
            (batch_size,),
            value,
            device=x1.device,
            dtype=x1.dtype,
        )

    def _time_like(timestep: torch.Tensor, x_t: torch.Tensor) -> torch.Tensor:
        return timestep.view(batch_size, *([1] * (x_t.ndim - 1)))

    adjs: list[torch.Tensor] = [torch.empty_like(x1) for _ in range(num_steps + 1)]
    adjs[-1] = (-Q_grad_at_1.to(device=x1.device, dtype=x1.dtype) / lambda_t).detach()

    for step in range(num_steps, 0, -1):
        timestep = _time(step / num_steps)
        x_t = traj[step].detach().requires_grad_(True)
        adj_next = adjs[step].detach()

        def beta_drift_at_x(input_x: torch.Tensor) -> torch.Tensor:
            velocity = f_beta_fn(obs, input_x, timestep)
            if velocity.shape != input_x.shape:
                raise ValueError(
                    "f_beta_fn must return the same shape as its x_t input, "
                    f"got {tuple(velocity.shape)} and expected "
                    f"{tuple(input_x.shape)}"
                )
            velocity = velocity.to(device=input_x.device, dtype=input_x.dtype)
            return 2.0 * velocity - input_x / _time_like(timestep, input_x)

        _, vjp_x = torch.autograd.functional.vjp(
            beta_drift_at_x,
            x_t,
            v=adj_next,
            create_graph=False,
            strict=False,
        )
        adjs[step - 1] = (adj_next + h * vjp_x).detach()

    return traj, torch.stack(adjs, dim=0)
